### ISSUE TITLE
Doesn't work in PHP 7.3

### ISSUE THREAD

**Issue by azurit** [Whissi/realpath_turbo#15] opened 2020-01-04 09:22 UTC
Trying this on PHP 7.3.13 but it seems to not work at all:
 - version 2.0.0
 - open_basedir is unset
 - realpath_turbo.open_basedir is set
 - i can't see realpath_turbo.open_basedir in phpinfo
 - open_basedir is empty in phpinfo
 - i can access files/dirs outside directories set in realpath_turbo.open_basedir

It is supposed to work in PHP 7.3?

**Comment by szepeviktor** [comment] 2020-01-04 09:23
removed from CI
https://github.com/Whissi/realpath_turbo/commit/1479909728339e30f2715db9df4cdb41c17064a7#diff-354f30a63fb0907d4ad57269548329e3L19

**Comment by azurit** [comment] 2020-01-04 09:25
Sorry but i don't understand: Was is CI? What was removed?

**Comment by azurit** [comment] 2020-01-04 09:26
I'm running PHP as FPM.

**Comment by azurit** [comment] 2020-01-04 09:30
If i understand that commit ok, you have dropped support for PHP 7.3. Can i ask why? 7.2 and 7.4 are both supported. Thanks for info.

**Comment by szepeviktor** [comment] 2020-01-04 09:31
"CI" is continuous integration.
This project uses TravisCI https://travis-ci.org/Whissi/realpath_turbo/builds/618366170

PHP 7.3 was removed: so tests do not run on PHP 7.3
See Travis for tested PHP versions.

**Comment by szepeviktor** [comment] 2020-01-04 09:34
> If i understand that commit ok, you have dropped support for PHP 7.3

It wasn't I, it was @Whissi

**Comment by azurit** [comment] 2020-01-04 09:35
Sorry, didn't notice you are not a developer of realpath_turbo.

@Whissi, can i ask why you have dropped support for PHP 7.3? Thank you.

**Comment by szepeviktor** [comment] 2020-01-04 09:39
Only the tests do not run on 7.3.
It does not necessarily mean that support is dropped.

**Comment by azurit** [comment] 2020-01-04 10:49
I was able to resolve this. The main problem is that the whole compilation and installation process ignores 'phpize' command used if there are multiple PHP versions in the system - it simply takes the newest version (in my case, i did 'phpize7.3' but everything was compiled and installed for 7.4). The switch '--with-php-config' for 'configure' commad must be used. Is this a bug?

**Comment by Whissi** [comment] 2020-01-04 13:20
Like @szepeviktor said, only test coverage was dropped. Thanks for noticing, should be fixed now.

If realpath_turbo doesn't show up in `phpinfo()` it's just not loaded, that simple :)

>  The main problem is that the whole compilation and installation process ignores 'phpize' command used if there are multiple PHP versions in the system - it simply takes the newest version (in my case, i did 'phpize7.3' but everything was compiled and installed for 7.4). The switch '--with-php-config' for 'configure' commad must be used. Is this a bug?

No, not a bug and nothing I can do about. That's how the PHP PECL system works. If you have multiple PHP versions installed, it's your responsibility to mange them. Most distributions have own solutions for that (like `update-alternatives` on Debian-based systems). But you can always make sure that `phpsize` from version you want is first in path, e.g. do `export PATH=/path/to/phpsize/you/want/to/use:$PATH` first...

**Closed by Whissi** 2020-01-04 13:20 UTC

**Comment by azurit** [comment] 2020-01-04 14:12
Thank you!
